version: 2

sources:
  - name: zoomcamp
    database: kestra-de-zoomcamp-kenneth
    schema: zoomcamp
    tables:
      - name: weather_data
        description: "Weather data table containing place, value, unit, and recordTime."
        columns:
          - name: parameter
            description: "temperature or humidity"
            tests:
              - not_null  


          - name: place
            description: "The location or place associated with the weather record."
            tests:
              - not_null

          - name: value
            description: "The numerical value associated with the weather record."
            tests:
              - not_null

          - name: unit
            description: "The unit of measurement for the value (e.g., 'C' for Celsius or 'F' for Fahrenheit)."
            tests:
              - not_null
              - accepted_values:
                  values: ['C', 'percent']

          - name: record_time
            description: "The timestamp when the weather record was created."
            tests:
              - not_null